import pandas as pd
import sqlite3

# アップロードに用いるdbmap
excel_db_map = {
    'table_name': 'size_table_lite',
    'column': {
        'No': {'type': 'text', 'index': 1},
        'お名前': {'type': 'text', 'index': 2},
        '年齢': {'type': 'text', 'index': 3},
        '身長': {'type': 'text', 'index': 4},
        '年月日_1行目': {'type': 'text', 'index': 5},
        '上腕_右_床上_1行目': {'type': 'text', 'index': 6},
        '上腕_右_前_1行目': {'type': 'text', 'index': 7},
        '上腕_右_後_1行目': {'type': 'text', 'index': 8},
        '上腕_右_差_1行目': {'type': 'text', 'index': 9},
        '上腕_左_床上_1行目': {'type': 'text', 'index': 10},
        '上腕_左_前_1行目': {'type': 'text', 'index': 11},
        '上腕_左_後_1行目': {'type': 'text', 'index': 12},
        '上腕_左_差_1行目': {'type': 'text', 'index': 13},
        'トップ床上_床上_1行目': {'type': 'text', 'index': 14},
        'トップ床上_前_1行目': {'type': 'text', 'index': 15},
        'トップ床上_後_1行目': {'type': 'text', 'index': 16},
        'トップ床上_差_1行目': {'type': 'text', 'index': 17},
        'トップ_床上_1行目': {'type': 'text', 'index': 18},
        'トップ_前_1行目': {'type': 'text', 'index': 19},
        'トップ_後_1行目': {'type': 'text', 'index': 20},
        'トップ_差_1行目': {'type': 'text', 'index': 21},
        'アンダー_床上_1行目': {'type': 'text', 'index': 22},
        'アンダー_前_1行目': {'type': 'text', 'index': 23},
        'アンダー_後_1行目': {'type': 'text', 'index': 24},
        'アンダー_差_1行目': {'type': 'text', 'index': 25},
        'ウエスト床上_床上_1行目': {'type': 'text', 'index': 26},
        'ウエスト床上_前_1行目': {'type': 'text', 'index': 27},
        'ウエスト床上_後_1行目': {'type': 'text', 'index': 28},
        'ウエスト床上_差_1行目': {'type': 'text', 'index': 29},
        'ウエスト_床上_1行目': {'type': 'text', 'index': 30},
        'ウエスト_前_1行目': {'type': 'text', 'index': 31},
        'ウエスト_後_1行目': {'type': 'text', 'index': 32},
        'ウエスト_差_1行目': {'type': 'text', 'index': 33},
        '下腹部_床上_1行目': {'type': 'text', 'index': 34},
        '下腹部_前_1行目': {'type': 'text', 'index': 35},
        '下腹部_後_1行目': {'type': 'text', 'index': 36},
        '下腹部_差_1行目': {'type': 'text', 'index': 37},
        'ヒップ床上_床上_1行目': {'type': 'text', 'index': 38},
        'ヒップ床上_前_1行目': {'type': 'text', 'index': 39},
        'ヒップ床上_後_1行目': {'type': 'text', 'index': 40},
        'ヒップ床上_差_1行目': {'type': 'text', 'index': 41},
        'ヒップ_床上_1行目': {'type': 'text', 'index': 42},
        'ヒップ_前_1行目': {'type': 'text', 'index': 43},
        'ヒップ_後_1行目': {'type': 'text', 'index': 44},
        'ヒップ_差_1行目': {'type': 'text', 'index': 45},
        '大腿部_左_床上_1行目': {'type': 'text', 'index': 46},
        '大腿部_左_前_1行目': {'type': 'text', 'index': 47},
        '大腿部_左_後_1行目': {'type': 'text', 'index': 48},
        '大腿部_左_差_1行目': {'type': 'text', 'index': 49},
        '大腿部_右_床上_1行目': {'type': 'text', 'index': 50},
        '大腿部_右_前_1行目': {'type': 'text', 'index': 51},
        '大腿部_右_後_1行目': {'type': 'text', 'index': 52},
        '大腿部_右_差_1行目': {'type': 'text', 'index': 53},
        '膝上_左_床上_1行目': {'type': 'text', 'index': 54},
        '膝上_左_前_1行目': {'type': 'text', 'index': 55},
        '膝上_左_後_1行目': {'type': 'text', 'index': 56},
        '膝上_左_差_1行目': {'type': 'text', 'index': 57},
        '膝上_右_床上_1行目': {'type': 'text', 'index': 58},
        '膝上_右_前_1行目': {'type': 'text', 'index': 59},
        '膝上_右_後_1行目': {'type': 'text', 'index': 60},
        '膝上_右_差_1行目': {'type': 'text', 'index': 61},
        '下腿部_左_床上_1行目': {'type': 'text', 'index': 62},
        '下腿部_左_前_1行目': {'type': 'text', 'index': 63},
        '下腿部_左_後_1行目': {'type': 'text', 'index': 64},
        '下腿部_左_差_1行目': {'type': 'text', 'index': 65},
        '下腿部_右_床上_1行目': {'type': 'text', 'index': 66},
        '下腿部_右_前_1行目': {'type': 'text', 'index': 67},
        '下腿部_右_後_1行目': {'type': 'text', 'index': 68},
        '下腿部_右_差_1行目': {'type': 'text', 'index': 69},
        '足首_左_床上_1行目': {'type': 'text', 'index': 70},
        '足首_左_前_1行目': {'type': 'text', 'index': 71},
        '足首_左_後_1行目': {'type': 'text', 'index': 72},
        '足首_左_差_1行目': {'type': 'text', 'index': 73},
        '足首_右_床上_1行目': {'type': 'text', 'index': 74},
        '足首_右_前_1行目': {'type': 'text', 'index': 75},
        '足首_右_後_1行目': {'type': 'text', 'index': 76},
        '足首_右_差_1行目': {'type': 'text', 'index': 77},
        '確認サイン_1行目': {'type': 'text', 'index': 78},
        '担当者_1行目': {'type': 'text', 'index': 79},
        '年月日_2行目': {'type': 'text', 'index': 80},
        '上腕_右_床上_2行目': {'type': 'text', 'index': 81},
        '上腕_右_前_2行目': {'type': 'text', 'index': 82},
        '上腕_右_後_2行目': {'type': 'text', 'index': 83},
        '上腕_右_差_2行目': {'type': 'text', 'index': 84},
        '上腕_左_床上_2行目': {'type': 'text', 'index': 85},
        '上腕_左_前_2行目': {'type': 'text', 'index': 86},
        '上腕_左_後_2行目': {'type': 'text', 'index': 87},
        '上腕_左_差_2行目': {'type': 'text', 'index': 88},
        'トップ床上_床上_2行目': {'type': 'text', 'index': 89},
        'トップ床上_前_2行目': {'type': 'text', 'index': 90},
        'トップ床上_後_2行目': {'type': 'text', 'index': 91},
        'トップ床上_差_2行目': {'type': 'text', 'index': 92},
        'トップ_床上_2行目': {'type': 'text', 'index': 93},
        'トップ_前_2行目': {'type': 'text', 'index': 94},
        'トップ_後_2行目': {'type': 'text', 'index': 95},
        'トップ_差_2行目': {'type': 'text', 'index': 96},
        'アンダー_床上_2行目': {'type': 'text', 'index': 97},
        'アンダー_前_2行目': {'type': 'text', 'index': 98},
        'アンダー_後_2行目': {'type': 'text', 'index': 99},
        'アンダー_差_2行目': {'type': 'text', 'index': 100},
        'ウエスト床上_床上_2行目': {'type': 'text', 'index': 101},
        'ウエスト床上_前_2行目': {'type': 'text', 'index': 102},
        'ウエスト床上_後_2行目': {'type': 'text', 'index': 103},
        'ウエスト床上_差_2行目': {'type': 'text', 'index': 104},
        'ウエスト_床上_2行目': {'type': 'text', 'index': 105},
        'ウエスト_前_2行目': {'type': 'text', 'index': 106},
        'ウエスト_後_2行目': {'type': 'text', 'index': 107},
        'ウエスト_差_2行目': {'type': 'text', 'index': 108},
        '下腹部_床上_2行目': {'type': 'text', 'index': 109},
        '下腹部_前_2行目': {'type': 'text', 'index': 110},
        '下腹部_後_2行目': {'type': 'text', 'index': 111},
        '下腹部_差_2行目': {'type': 'text', 'index': 112},
        'ヒップ床上_床上_2行目': {'type': 'text', 'index': 113},
        'ヒップ床上_前_2行目': {'type': 'text', 'index': 114},
        'ヒップ床上_後_2行目': {'type': 'text', 'index': 115},
        'ヒップ床上_差_2行目': {'type': 'text', 'index': 116},
        'ヒップ_床上_2行目': {'type': 'text', 'index': 117},
        'ヒップ_前_2行目': {'type': 'text', 'index': 118},
        'ヒップ_後_2行目': {'type': 'text', 'index': 119},
        'ヒップ_差_2行目': {'type': 'text', 'index': 120},
        '大腿部_左_床上_2行目': {'type': 'text', 'index': 121},
        '大腿部_左_前_2行目': {'type': 'text', 'index': 122},
        '大腿部_左_後_2行目': {'type': 'text', 'index': 123},
        '大腿部_左_差_2行目': {'type': 'text', 'index': 124},
        '大腿部_右_床上_2行目': {'type': 'text', 'index': 125},
        '大腿部_右_前_2行目': {'type': 'text', 'index': 126},
        '大腿部_右_後_2行目': {'type': 'text', 'index': 127},
        '大腿部_右_差_2行目': {'type': 'text', 'index': 128},
        '膝上_左_床上_2行目': {'type': 'text', 'index': 129},
        '膝上_左_前_2行目': {'type': 'text', 'index': 130},
        '膝上_左_後_2行目': {'type': 'text', 'index': 131},
        '膝上_左_差_2行目': {'type': 'text', 'index': 132},
        '膝上_右_床上_2行目': {'type': 'text', 'index': 133},
        '膝上_右_前_2行目': {'type': 'text', 'index': 134},
        '膝上_右_後_2行目': {'type': 'text', 'index': 135},
        '膝上_右_差_2行目': {'type': 'text', 'index': 136},
        '下腿部_左_床上_2行目': {'type': 'text', 'index': 137},
        '下腿部_左_前_2行目': {'type': 'text', 'index': 138},
        '下腿部_左_後_2行目': {'type': 'text', 'index': 139},
        '下腿部_左_差_2行目': {'type': 'text', 'index': 140},
        '下腿部_右_床上_2行目': {'type': 'text', 'index': 141},
        '下腿部_右_前_2行目': {'type': 'text', 'index': 142},
        '下腿部_右_後_2行目': {'type': 'text', 'index': 143},
        '下腿部_右_差_2行目': {'type': 'text', 'index': 144},
        '足首_左_床上_2行目': {'type': 'text', 'index': 145},
        '足首_左_前_2行目': {'type': 'text', 'index': 146},
        '足首_左_後_2行目': {'type': 'text', 'index': 147},
        '足首_左_差_2行目': {'type': 'text', 'index': 148},
        '足首_右_床上_2行目': {'type': 'text', 'index': 149},
        '足首_右_前_2行目': {'type': 'text', 'index': 150},
        '足首_右_後_2行目': {'type': 'text', 'index': 151},
        '足首_右_差_2行目': {'type': 'text', 'index': 152},
        '確認サイン_2行目': {'type': 'text', 'index': 153},
        '担当者_2行目': {'type': 'text', 'index': 154},
        '年月日_3行目': {'type': 'text', 'index': 155},
        '上腕_右_床上_3行目': {'type': 'text', 'index': 156},
        '上腕_右_前_3行目': {'type': 'text', 'index': 157},
        '上腕_右_後_3行目': {'type': 'text', 'index': 158},
        '上腕_右_差_3行目': {'type': 'text', 'index': 159},
        '上腕_左_床上_3行目': {'type': 'text', 'index': 160},
        '上腕_左_前_3行目': {'type': 'text', 'index': 161},
        '上腕_左_後_3行目': {'type': 'text', 'index': 162},
        '上腕_左_差_3行目': {'type': 'text', 'index': 163},
        'トップ床上_床上_3行目': {'type': 'text', 'index': 164},
        'トップ床上_前_3行目': {'type': 'text', 'index': 165},
        'トップ床上_後_3行目': {'type': 'text', 'index': 166},
        'トップ床上_差_3行目': {'type': 'text', 'index': 167},
        'トップ_床上_3行目': {'type': 'text', 'index': 168},
        'トップ_前_3行目': {'type': 'text', 'index': 169},
        'トップ_後_3行目': {'type': 'text', 'index': 170},
        'トップ_差_3行目': {'type': 'text', 'index': 171},
        'アンダー_床上_3行目': {'type': 'text', 'index': 172},
        'アンダー_前_3行目': {'type': 'text', 'index': 173},
        'アンダー_後_3行目': {'type': 'text', 'index': 174},
        'アンダー_差_3行目': {'type': 'text', 'index': 175},
        'ウエスト床上_床上_3行目': {'type': 'text', 'index': 176},
        'ウエスト床上_前_3行目': {'type': 'text', 'index': 177},
        'ウエスト床上_後_3行目': {'type': 'text', 'index': 178},
        'ウエスト床上_差_3行目': {'type': 'text', 'index': 179},
        'ウエスト_床上_3行目': {'type': 'text', 'index': 180},
        'ウエスト_前_3行目': {'type': 'text', 'index': 181},
        'ウエスト_後_3行目': {'type': 'text', 'index': 182},
        'ウエスト_差_3行目': {'type': 'text', 'index': 183},
        '下腹部_床上_3行目': {'type': 'text', 'index': 184},
        '下腹部_前_3行目': {'type': 'text', 'index': 185},
        '下腹部_後_3行目': {'type': 'text', 'index': 186},
        '下腹部_差_3行目': {'type': 'text', 'index': 187},
        'ヒップ床上_床上_3行目': {'type': 'text', 'index': 188},
        'ヒップ床上_前_3行目': {'type': 'text', 'index': 189},
        'ヒップ床上_後_3行目': {'type': 'text', 'index': 190},
        'ヒップ床上_差_3行目': {'type': 'text', 'index': 191},
        'ヒップ_床上_3行目': {'type': 'text', 'index': 192},
        'ヒップ_前_3行目': {'type': 'text', 'index': 193},
        'ヒップ_後_3行目': {'type': 'text', 'index': 194},
        'ヒップ_差_3行目': {'type': 'text', 'index': 195},
        '大腿部_左_床上_3行目': {'type': 'text', 'index': 196},
        '大腿部_左_前_3行目': {'type': 'text', 'index': 197},
        '大腿部_左_後_3行目': {'type': 'text', 'index': 198},
        '大腿部_左_差_3行目': {'type': 'text', 'index': 199},
        '大腿部_右_床上_3行目': {'type': 'text', 'index': 200},
        '大腿部_右_前_3行目': {'type': 'text', 'index': 201},
        '大腿部_右_後_3行目': {'type': 'text', 'index': 202},
        '大腿部_右_差_3行目': {'type': 'text', 'index': 203},
        '膝上_左_床上_3行目': {'type': 'text', 'index': 204},
        '膝上_左_前_3行目': {'type': 'text', 'index': 205},
        '膝上_左_後_3行目': {'type': 'text', 'index': 206},
        '膝上_左_差_3行目': {'type': 'text', 'index': 207},
        '膝上_右_床上_3行目': {'type': 'text', 'index': 208},
        '膝上_右_前_3行目': {'type': 'text', 'index': 209},
        '膝上_右_後_3行目': {'type': 'text', 'index': 210},
        '膝上_右_差_3行目': {'type': 'text', 'index': 211},
        '下腿部_左_床上_3行目': {'type': 'text', 'index': 212},
        '下腿部_左_前_3行目': {'type': 'text', 'index': 213},
        '下腿部_左_後_3行目': {'type': 'text', 'index': 214},
        '下腿部_左_差_3行目': {'type': 'text', 'index': 215},
        '下腿部_右_床上_3行目': {'type': 'text', 'index': 216},
        '下腿部_右_前_3行目': {'type': 'text', 'index': 217},
        '下腿部_右_後_3行目': {'type': 'text', 'index': 218},
        '下腿部_右_差_3行目': {'type': 'text', 'index': 219},
        '足首_左_床上_3行目': {'type': 'text', 'index': 220},
        '足首_左_前_3行目': {'type': 'text', 'index': 221},
        '足首_左_後_3行目': {'type': 'text', 'index': 222},
        '足首_左_差_3行目': {'type': 'text', 'index': 223},
        '足首_右_床上_3行目': {'type': 'text', 'index': 224},
        '足首_右_前_3行目': {'type': 'text', 'index': 225},
        '足首_右_後_3行目': {'type': 'text', 'index': 226},
        '足首_右_差_3行目': {'type': 'text', 'index': 227},
        '確認サイン_3行目': {'type': 'text', 'index': 228},
        '担当者_3行目': {'type': 'text', 'index': 229},
        '年月日_4行目': {'type': 'text', 'index': 230},
        '上腕_右_床上_4行目': {'type': 'text', 'index': 231},
        '上腕_右_前_4行目': {'type': 'text', 'index': 232},
        '上腕_右_後_4行目': {'type': 'text', 'index': 233},
        '上腕_右_差_4行目': {'type': 'text', 'index': 234},
        '上腕_左_床上_4行目': {'type': 'text', 'index': 235},
        '上腕_左_前_4行目': {'type': 'text', 'index': 236},
        '上腕_左_後_4行目': {'type': 'text', 'index': 237},
        '上腕_左_差_4行目': {'type': 'text', 'index': 238},
        'トップ床上_床上_4行目': {'type': 'text', 'index': 239},
        'トップ床上_前_4行目': {'type': 'text', 'index': 240},
        'トップ床上_後_4行目': {'type': 'text', 'index': 241},
        'トップ床上_差_4行目': {'type': 'text', 'index': 242},
        'トップ_床上_4行目': {'type': 'text', 'index': 243},
        'トップ_前_4行目': {'type': 'text', 'index': 244},
        'トップ_後_4行目': {'type': 'text', 'index': 245},
        'トップ_差_4行目': {'type': 'text', 'index': 246},
        'アンダー_床上_4行目': {'type': 'text', 'index': 247},
        'アンダー_前_4行目': {'type': 'text', 'index': 248},
        'アンダー_後_4行目': {'type': 'text', 'index': 249},
        'アンダー_差_4行目': {'type': 'text', 'index': 250},
        'ウエスト床上_床上_4行目': {'type': 'text', 'index': 251},
        'ウエスト床上_前_4行目': {'type': 'text', 'index': 252},
        'ウエスト床上_後_4行目': {'type': 'text', 'index': 253},
        'ウエスト床上_差_4行目': {'type': 'text', 'index': 254},
        'ウエスト_床上_4行目': {'type': 'text', 'index': 255},
        'ウエスト_前_4行目': {'type': 'text', 'index': 256},
        'ウエスト_後_4行目': {'type': 'text', 'index': 257},
        'ウエスト_差_4行目': {'type': 'text', 'index': 258},
        '下腹部_床上_4行目': {'type': 'text', 'index': 259},
        '下腹部_前_4行目': {'type': 'text', 'index': 260},
        '下腹部_後_4行目': {'type': 'text', 'index': 261},
        '下腹部_差_4行目': {'type': 'text', 'index': 262},
        'ヒップ床上_床上_4行目': {'type': 'text', 'index': 263},
        'ヒップ床上_前_4行目': {'type': 'text', 'index': 264},
        'ヒップ床上_後_4行目': {'type': 'text', 'index': 265},
        'ヒップ床上_差_4行目': {'type': 'text', 'index': 266},
        'ヒップ_床上_4行目': {'type': 'text', 'index': 267},
        'ヒップ_前_4行目': {'type': 'text', 'index': 268},
        'ヒップ_後_4行目': {'type': 'text', 'index': 269},
        'ヒップ_差_4行目': {'type': 'text', 'index': 270},
        '大腿部_左_床上_4行目': {'type': 'text', 'index': 271},
        '大腿部_左_前_4行目': {'type': 'text', 'index': 272},
        '大腿部_左_後_4行目': {'type': 'text', 'index': 273},
        '大腿部_左_差_4行目': {'type': 'text', 'index': 274},
        '大腿部_右_床上_4行目': {'type': 'text', 'index': 275},
        '大腿部_右_前_4行目': {'type': 'text', 'index': 276},
        '大腿部_右_後_4行目': {'type': 'text', 'index': 277},
        '大腿部_右_差_4行目': {'type': 'text', 'index': 278},
        '膝上_左_床上_4行目': {'type': 'text', 'index': 279},
        '膝上_左_前_4行目': {'type': 'text', 'index': 280},
        '膝上_左_後_4行目': {'type': 'text', 'index': 281},
        '膝上_左_差_4行目': {'type': 'text', 'index': 282},
        '膝上_右_床上_4行目': {'type': 'text', 'index': 283},
        '膝上_右_前_4行目': {'type': 'text', 'index': 284},
        '膝上_右_後_4行目': {'type': 'text', 'index': 285},
        '膝上_右_差_4行目': {'type': 'text', 'index': 286},
        '下腿部_左_床上_4行目': {'type': 'text', 'index': 287},
        '下腿部_左_前_4行目': {'type': 'text', 'index': 288},
        '下腿部_左_後_4行目': {'type': 'text', 'index': 289},
        '下腿部_左_差_4行目': {'type': 'text', 'index': 290},
        '下腿部_右_床上_4行目': {'type': 'text', 'index': 291},
        '下腿部_右_前_4行目': {'type': 'text', 'index': 292},
        '下腿部_右_後_4行目': {'type': 'text', 'index': 293},
        '下腿部_右_差_4行目': {'type': 'text', 'index': 294},
        '足首_左_床上_4行目': {'type': 'text', 'index': 295},
        '足首_左_前_4行目': {'type': 'text', 'index': 296},
        '足首_左_後_4行目': {'type': 'text', 'index': 297},
        '足首_左_差_4行目': {'type': 'text', 'index': 298},
        '足首_右_床上_4行目': {'type': 'text', 'index': 299},
        '足首_右_前_4行目': {'type': 'text', 'index': 300},
        '足首_右_後_4行目': {'type': 'text', 'index': 301},
        '足首_右_差_4行目': {'type': 'text', 'index': 302},
        '確認サイン_4行目': {'type': 'text', 'index': 303},
        '担当者_4行目': {'type': 'text', 'index': 304},
        '年月日_5行目': {'type': 'text', 'index': 305},
        '上腕_右_床上_5行目': {'type': 'text', 'index': 306},
        '上腕_右_前_5行目': {'type': 'text', 'index': 307},
        '上腕_右_後_5行目': {'type': 'text', 'index': 308},
        '上腕_右_差_5行目': {'type': 'text', 'index': 309},
        '上腕_左_床上_5行目': {'type': 'text', 'index': 310},
        '上腕_左_前_5行目': {'type': 'text', 'index': 311},
        '上腕_左_後_5行目': {'type': 'text', 'index': 312},
        '上腕_左_差_5行目': {'type': 'text', 'index': 313},
        'トップ床上_床上_5行目': {'type': 'text', 'index': 314},
        'トップ床上_前_5行目': {'type': 'text', 'index': 315},
        'トップ床上_後_5行目': {'type': 'text', 'index': 316},
        'トップ床上_差_5行目': {'type': 'text', 'index': 317},
        'トップ_床上_5行目': {'type': 'text', 'index': 318},
        'トップ_前_5行目': {'type': 'text', 'index': 319},
        'トップ_後_5行目': {'type': 'text', 'index': 320},
        'トップ_差_5行目': {'type': 'text', 'index': 321},
        'アンダー_床上_5行目': {'type': 'text', 'index': 322},
        'アンダー_前_5行目': {'type': 'text', 'index': 323},
        'アンダー_後_5行目': {'type': 'text', 'index': 324},
        'アンダー_差_5行目': {'type': 'text', 'index': 325},
        'ウエスト床上_床上_5行目': {'type': 'text', 'index': 326},
        'ウエスト床上_前_5行目': {'type': 'text', 'index': 327},
        'ウエスト床上_後_5行目': {'type': 'text', 'index': 328},
        'ウエスト床上_差_5行目': {'type': 'text', 'index': 329},
        'ウエスト_床上_5行目': {'type': 'text', 'index': 330},
        'ウエスト_前_5行目': {'type': 'text', 'index': 331},
        'ウエスト_後_5行目': {'type': 'text', 'index': 332},
        'ウエスト_差_5行目': {'type': 'text', 'index': 333},
        '下腹部_床上_5行目': {'type': 'text', 'index': 334},
        '下腹部_前_5行目': {'type': 'text', 'index': 335},
        '下腹部_後_5行目': {'type': 'text', 'index': 336},
        '下腹部_差_5行目': {'type': 'text', 'index': 337},
        'ヒップ床上_床上_5行目': {'type': 'text', 'index': 338},
        'ヒップ床上_前_5行目': {'type': 'text', 'index': 339},
        'ヒップ床上_後_5行目': {'type': 'text', 'index': 340},
        'ヒップ床上_差_5行目': {'type': 'text', 'index': 341},
        'ヒップ_床上_5行目': {'type': 'text', 'index': 342},
        'ヒップ_前_5行目': {'type': 'text', 'index': 343},
        'ヒップ_後_5行目': {'type': 'text', 'index': 344},
        'ヒップ_差_5行目': {'type': 'text', 'index': 345},
        '大腿部_左_床上_5行目': {'type': 'text', 'index': 346},
        '大腿部_左_前_5行目': {'type': 'text', 'index': 347},
        '大腿部_左_後_5行目': {'type': 'text', 'index': 348},
        '大腿部_左_差_5行目': {'type': 'text', 'index': 349},
        '大腿部_右_床上_5行目': {'type': 'text', 'index': 350},
        '大腿部_右_前_5行目': {'type': 'text', 'index': 351},
        '大腿部_右_後_5行目': {'type': 'text', 'index': 352},
        '大腿部_右_差_5行目': {'type': 'text', 'index': 353},
        '膝上_左_床上_5行目': {'type': 'text', 'index': 354},
        '膝上_左_前_5行目': {'type': 'text', 'index': 355},
        '膝上_左_後_5行目': {'type': 'text', 'index': 356},
        '膝上_左_差_5行目': {'type': 'text', 'index': 357},
        '膝上_右_床上_5行目': {'type': 'text', 'index': 358},
        '膝上_右_前_5行目': {'type': 'text', 'index': 359},
        '膝上_右_後_5行目': {'type': 'text', 'index': 360},
        '膝上_右_差_5行目': {'type': 'text', 'index': 361},
        '下腿部_左_床上_5行目': {'type': 'text', 'index': 362},
        '下腿部_左_前_5行目': {'type': 'text', 'index': 363},
        '下腿部_左_後_5行目': {'type': 'text', 'index': 364},
        '下腿部_左_差_5行目': {'type': 'text', 'index': 365},
        '下腿部_右_床上_5行目': {'type': 'text', 'index': 366},
        '下腿部_右_前_5行目': {'type': 'text', 'index': 367},
        '下腿部_右_後_5行目': {'type': 'text', 'index': 368},
        '下腿部_右_差_5行目': {'type': 'text', 'index': 369},
        '足首_左_床上_5行目': {'type': 'text', 'index': 370},
        '足首_左_前_5行目': {'type': 'text', 'index': 371},
        '足首_左_後_5行目': {'type': 'text', 'index': 372},
        '足首_左_差_5行目': {'type': 'text', 'index': 373},
        '足首_右_床上_5行目': {'type': 'text', 'index': 374},
        '足首_右_前_5行目': {'type': 'text', 'index': 375},
        '足首_右_後_5行目': {'type': 'text', 'index': 376},
        '足首_右_差_5行目': {'type': 'text', 'index': 377},
        '確認サイン_5行目': {'type': 'text', 'index': 378},
        '担当者_5行目': {'type': 'text', 'index': 379},
        '年月日_6行目': {'type': 'text', 'index': 380},
        '上腕_右_床上_6行目': {'type': 'text', 'index': 381},
        '上腕_右_前_6行目': {'type': 'text', 'index': 382},
        '上腕_右_後_6行目': {'type': 'text', 'index': 383},
        '上腕_右_差_6行目': {'type': 'text', 'index': 384},
        '上腕_左_床上_6行目': {'type': 'text', 'index': 385},
        '上腕_左_前_6行目': {'type': 'text', 'index': 386},
        '上腕_左_後_6行目': {'type': 'text', 'index': 387},
        '上腕_左_差_6行目': {'type': 'text', 'index': 388},
        'トップ床上_床上_6行目': {'type': 'text', 'index': 389},
        'トップ床上_前_6行目': {'type': 'text', 'index': 390},
        'トップ床上_後_6行目': {'type': 'text', 'index': 391},
        'トップ床上_差_6行目': {'type': 'text', 'index': 392},
        'トップ_床上_6行目': {'type': 'text', 'index': 393},
        'トップ_前_6行目': {'type': 'text', 'index': 394},
        'トップ_後_6行目': {'type': 'text', 'index': 395},
        'トップ_差_6行目': {'type': 'text', 'index': 396},
        'アンダー_床上_6行目': {'type': 'text', 'index': 397},
        'アンダー_前_6行目': {'type': 'text', 'index': 398},
        'アンダー_後_6行目': {'type': 'text', 'index': 399},
        'アンダー_差_6行目': {'type': 'text', 'index': 400},
        'ウエスト床上_床上_6行目': {'type': 'text', 'index': 401},
        'ウエスト床上_前_6行目': {'type': 'text', 'index': 402},
        'ウエスト床上_後_6行目': {'type': 'text', 'index': 403},
        'ウエスト床上_差_6行目': {'type': 'text', 'index': 404},
        'ウエスト_床上_6行目': {'type': 'text', 'index': 405},
        'ウエスト_前_6行目': {'type': 'text', 'index': 406},
        'ウエスト_後_6行目': {'type': 'text', 'index': 407},
        'ウエスト_差_6行目': {'type': 'text', 'index': 408},
        '下腹部_床上_6行目': {'type': 'text', 'index': 409},
        '下腹部_前_6行目': {'type': 'textt', 'index': 410},
        '下腹部_後_6行目': {'type': 'textt', 'index': 411},
        '下腹部_差_6行目': {'type': 'textt', 'index': 412},
        'ヒップ床上_床上_6行目': {'type': 'text', 'index': 413},
        'ヒップ床上_前_6行目': {'type': 'text', 'index': 414},
        'ヒップ床上_後_6行目': {'type': 'text', 'index': 415},
        'ヒップ床上_差_6行目': {'type': 'text', 'index': 416},
        'ヒップ_床上_6行目': {'type': 'text', 'index': 417},
        'ヒップ_前_6行目': {'type': 'text', 'index': 418},
        'ヒップ_後_6行目': {'type': 'text', 'index': 419},
        'ヒップ_差_6行目': {'type': 'text', 'index': 420},
        '大腿部_左_床上_6行目': {'type': 'text', 'index': 421},
        '大腿部_左_前_6行目': {'type': 'text', 'index': 422},
        '大腿部_左_後_6行目': {'type': 'text', 'index': 423},
        '大腿部_左_差_6行目': {'type': 'text', 'index': 424},
        '大腿部_右_床上_6行目': {'type': 'text', 'index': 425},
        '大腿部_右_前_6行目': {'type': 'text', 'index': 426},
        '大腿部_右_後_6行目': {'type': 'text', 'index': 427},
        '大腿部_右_差_6行目': {'type': 'text', 'index': 428},
        '膝上_左_床上_6行目': {'type': 'text', 'index': 429},
        '膝上_左_前_6行目': {'type': 'text', 'index': 430},
        '膝上_左_後_6行目': {'type': 'text', 'index': 431},
        '膝上_左_差_6行目': {'type': 'text', 'index': 432},
        '膝上_右_床上_6行目': {'type': 'text', 'index': 433},
        '膝上_右_前_6行目': {'type': 'text', 'index': 434},
        '膝上_右_後_6行目': {'type': 'text', 'index': 435},
        '膝上_右_差_6行目': {'type': 'text', 'index': 436},
        '下腿部_左_床上_6行目': {'type': 'text', 'index': 437},
        '下腿部_左_前_6行目': {'type': 'text', 'index': 438},
        '下腿部_左_後_6行目': {'type': 'text', 'index': 439},
        '下腿部_左_差_6行目': {'type': 'text', 'index': 440},
        '下腿部_右_床上_6行目': {'type': 'text', 'index': 441},
        '下腿部_右_前_6行目': {'type': 'text', 'index': 442},
        '下腿部_右_後_6行目': {'type': 'text', 'index': 443},
        '下腿部_右_差_6行目': {'type': 'text', 'index': 444},
        '足首_左_床上_6行目': {'type': 'text', 'index': 445},
        '足首_左_前_6行目': {'type': 'text', 'index': 446},
        '足首_左_後_6行目': {'type': 'text', 'index': 447},
        '足首_左_差_6行目': {'type': 'text', 'index': 448},
        '足首_右_床上_6行目': {'type': 'text', 'index': 449},
        '足首_右_前_6行目': {'type': 'text', 'index': 450},
        '足首_右_後_6行目': {'type': 'text', 'index': 451},
        '足首_右_差_6行目': {'type': 'text', 'index': 452},
        '確認サイン_6行目': {'type': 'text', 'index': 453},
        '担当者_6行目': {'type': 'text', 'index': 454},
    }
}


# データフレームをデータベースへアップロード
def db_insert(db, db_map):
    # conn = sqlite3.connect('S:/個人作業用/渡邊/ワールドジャパン/sqlite3/salon_J.db')
    conn = sqlite3.connect('S:/個人作業用/渡邊/ワールドジャパン/sqlite3/salon_all.db')
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    # 関数db_initを呼び出し
    db_init(db_map, cur)
    col_name = []
    val = []
    table_name = db_map['table_name']

    for k, v in db_map['column'].items():
        col_name.append(k)
        val.append(v['index'])
    
    col_names = ','.join(col_name)

    flag = 0

    for r in db.iterrows():
        values = []
        if r[1][0] is None:
            flag += 1
        else:
            flag = 0
            for v in val:
                cell_val = r[1][v-1]
                if type(cell_val) is not str and type(cell_val) is not int and cell_val is not None:
                    values.append(str(cell_val))
                else:
                    values.append(cell_val)

            place_holder = ','.join('?'*len(values))
            sql = f'INSERT INTO {table_name} ({col_names}) VALUES({place_holder})'
            cur.execute(sql, tuple(values))
        
        if flag == 2:
            break

    conn.commit()
    cur.close()
    conn.close()


# 既存のテーブルの値を削除
def db_init(db_map, db):
    param = []
    table_name = db_map['table_name']

    for k, v in db_map['column'].items():
        param.append(f"{k} {v['type']}")

    params = ','.join(param)

    db.execute(f'CREATE TABLE IF NOT EXISTS {table_name}({params})')
    db.execute(f'DELETE FROM {table_name}')


# excelファイルの内容を読み込み
wb_1 = pd.read_excel('S:/個人作業用/渡邊/ワールドジャパン/学習用データ/サロンカルテデータ_相馬さん/2フォーマット(潮永さん）/【J】サイズチェック表完成.xlsx', sheet_name='Sheet1', header=1)
wb_2 = pd.read_excel('S:/個人作業用/渡邊/ワールドジャパン/学習用データ/サロンカルテデータ_相馬さん/2フォーマット(渡部さん)/【J】サイズチェック表完成.xlsx', sheet_name='Sheet1', header=1)
wb_3 = pd.read_excel('S:/個人作業用/渡邊/ワールドジャパン/学習用データ/サロンカルテデータ_相馬さん/2フォーマット(柏葉さん)/【J】サイズチェック表完成.xlsx', sheet_name='Sheet1', header=1)
wb_4 = pd.read_excel('S:/個人作業用/渡邊/ワールドジャパン/学習用データ/サロンカルテデータ_相馬さん/慶野さん/【J】サイズチェック表完成.xlsx', sheet_name='Sheet1', header=1)
wb_5 = pd.read_excel('S:/個人作業用/渡邊/ワールドジャパン/学習用データ/サロンカルテデータ_相馬さん/佐藤さん/【J】サイズチェック表完成.xlsx', sheet_name='Sheet1', header=1)

#データフレームを結合
wb = pd.concat([wb_1, wb_2, wb_3, wb_4, wb_5])

wb = wb.rename(columns={'NO.' : 'No'})

# 不要な値を含む行を削除
wb = wb.dropna(subset=['No'])
wb = wb.drop_duplicates(subset='No', keep='last')

# 関数db_insertの呼び出し
db_insert(wb, excel_db_map)